language: en
pipeline:
  - name: "SpacyNLP"
    model: "en_core_web_sm"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "DIETClassifier"
    epochs: 100
  - name: "EntitySynonymMapper"

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    epochs: 50
  - name: TEDPolicy
    max_history: 5
    epochs: 100
